### ISSUE TITLE
Exception initializing a second app

### ISSUE THREAD

**Issue by gmacon** [nickw444/flask-ldap3-login#40] opened 2018-09-12 21:00 UTC
If you initialize LDAP3LoginManager on a second app after using the connection on the first app it raises an exception:

Code to reproduce:

```python
from flask import Flask
from flask_ldap3_login import LDAP3LoginManager

manager = LDAP3LoginManager()

app1 = Flask("one")
app1.config["LDAP_HOST"] = "localhost"
print("init one")
manager.init_app(app1)
with app1.app_context():
    print("connection one")
    manager.connection

app2 = Flask("two")
app2.config["LDAP_HOST"] = "localhost"
print("init two")
manager.init_app(app2)
```

output (on Python 3.7.0):

```
init one
connection one
init two
Traceback (most recent call last):
  File "repro.py", line 17, in <module>
    manager.init_app(app2)
  File ".../site-packages/flask_ldap3_login/__init__.py", line 77, in init_app
    self._server_pool.remove(s)
  File ".../site-packages/ldap3/core/pooling.py", line 285, in remove
    self.pool_states[connection].refresh()
  File ".../site-packages/ldap3/core/pooling.py", line 67, in refresh
    self.last_used_server = randint(0, len(self.servers) - 1)
  File ".../random.py", line 222, in randint
    return self.randrange(a, b+1)
  File ".../random.py", line 200, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,0, 0)
```

It looks like the fix here is to store the necessary state on the app context instead of on LDAP3LoginManager.

~~I'll try to find some time soon to put together a PR for this; please let me know if you have any comments.~~

Edit: After discussing with the other engineers on my project, we've decided to drop the dependency on Flask-LDAP3-Login, so I likely won't be trying to find time to open a PR for this any more.

**Comment by nickw444** [comment] 2018-09-16 17:50
Thanks for the report. Sad to hear you won’t be using the library in your app, but very understandable if you have the manpower available to implement this functionality in-house. Out of interest - was this bug the reason for not adopting the library, or was it because implementing LDAP in-house is more desired for any reason in particular? 

I’ll leave this open as it represents technical debt for a very niche bug, and address it at a point in the future.

**Comment by gmacon** [comment] 2018-09-22 18:06
We had started the implementation with the library, but it was on the edge of saving time/effort. This bug tipped us to the other side. We ended up vendoring the part of this library we wanted to use and making it work for multiple applications without worrying about completely breaking init_config (which was what happened when I tried to implement a PR).

**Comment by nickw444** [comment] 2018-09-26 11:46
A workaround for this issue until it is fixed would be to have two instances of `LDAP3LoginManager`, one for each app.

```python
from flask import Flask
from flask_ldap3_login import LDAP3LoginManager

manager1 = LDAP3LoginManager()
manager2 = LDAP3LoginManager()

app1 = Flask("one")
app1.config["LDAP_HOST"] = "ldap.forumsys.com"
print("init one")
manager1.init_app(app1)
with app1.app_context():
    print("connection one")
    manager1.connection

app2 = Flask("two")
app2.config["LDAP_HOST"] = "ldap.forumsys.com"
print("init two")
manager2.init_app(app2)
```

This isn't ideal, but it appears that other extensions that conform to the app factory pattern have this pitfall;

- flask-security - [keeps reference](https://github.com/mattupstate/flask-security/blob/develop/flask_security/core.py#L511-L519) to the app passed as `self.app`

(okay, I looked at a few big names (flask-sqlalchemy, flask-login, flask-mail, flask-limiter) and that was the only one).

The [flask docs](http://flask.pocoo.org/docs/0.12/extensiondev/#the-extension-code) state that:

>As you noticed, `init_app` does not assign app to self. This is intentional! Class based Flask extensions must only store the application on the object when the application was passed to the constructor. This tells the extension: I am not interested in using multiple applications.
>
>When the extension needs to find the current application and it does not have a reference to it, it must either use the current_app context local or change the API in a way that you can pass the application explicitly.

So this is something that will need to be addressed in the future, but until there exists a pressing requirement to do so, I will close this issue since a workaround exists.

**Comment by psychomantys** [comment] 2018-11-30 13:05
Uhum, i think I crossed with this error, but in a different way. And the workaround will not work for my case.

I was implementing tests on my application. In a test enviroment, the flask server can be started and killed a few times.

Always on the second execution the server dont work anymore.

This kind of behaviour make tests not easy to make...

I dont know if this is a ldap3 problem or something in this plugin....

The traceback of exception:

```
vf/__init__.py:49: in create_app
    ldap_manager.init_app(app)
../../../.local/share/virtualenvs//lib/python3.7/site-packages/flask_ldap3_login/__init__.py:77: in init_app
    self._server_pool.remove(s)
../../../.local/share/virtualenvs//lib/python3.7/site-packages/ldap3/core/pooling.py:285: in remove
    self.pool_states[connection].refresh()
../../../.local/share/virtualenvs/vf-CMjiR2h9/lib/python3.7/site-packages/ldap3/core/pooling.py:67: in refresh
    self.last_used_server = randint(0, len(self.servers) - 1)
../../../.local/share/virtualenvs/vf-CMjiR2h9/lib/python3.7/random.py:222: in randint
    return self.randrange(a, b+1)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <random.Random object at 0x55f3a6c6f1b8>, start = 0, stop = 0, step = 1, _int = <class 'int'>

    def randrange(self, start, stop=None, step=1, _int=int):
        """Choose a random item from range(start, stop[, step]).
    
        This fixes the problem with randint() which includes the
        endpoint; in Python this is usually not what you want.
    
        """
    
        # This code is a bit messy to make it fast for the
        # common case while still doing adequate error checking.
        istart = _int(start)
        if istart != start:
            raise ValueError("non-integer arg 1 for randrange()")
        if stop is None:
            if istart > 0:
                return self._randbelow(istart)
            raise ValueError("empty range for randrange()")
    
        # stop argument supplied.
        istop = _int(stop)
        if istop != stop:
            raise ValueError("non-integer stop for randrange()")
        width = istop - istart
        if step == 1 and width > 0:
            return istart + self._randbelow(width)
        if step == 1:
>           raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
E           ValueError: empty range for randrange() (0,0, 0)

../../../.local/share/virtualenvs/vf-CMjiR2h9/lib/python3.7/random.py:200: ValueError
================================================================== warnings summary ===================================================================
tests/test_login.py::test_login_logout
  /home/psycho/.local/share/virtualenvs/vf-CMjiR2h9/lib/python3.7/site-packages/sqlalchemy/orm/events.py:1853: DeprecationWarning: invalid escape sequence \D
    """
  /home/psycho/.local/share/virtualenvs/vf-CMjiR2h9/lib/python3.7/site-packages/ldap3/protocol/formatters/validators.py:355: DeprecationWarning: invalid escape sequence \9
    """
  /home/psycho/.local/share/virtualenvs/vf-CMjiR2h9/lib/python3.7/site-packages/pyasn1/type/constraint.py:130: DeprecationWarning: invalid escape sequence \*
    """
  /home/psycho/.local/share/virtualenvs/vf-CMjiR2h9/lib/python3.7/site-packages/pyasn1/type/constraint.py:175: DeprecationWarning: invalid escape sequence \*
    """
  /home/psycho/.local/share/virtualenvs/vf-CMjiR2h9/lib/python3.7/site-packages/pyasn1/type/constraint.py:334: DeprecationWarning: invalid escape sequence \*
    """
  /home/psycho/.local/share/virtualenvs/vf-CMjiR2h9/lib/python3.7/site-packages/pyasn1/type/constraint.py:494: DeprecationWarning: invalid escape sequence \*
    """
  /home/psycho/.local/share/virtualenvs/vf-CMjiR2h9/lib/python3.7/site-packages/pyasn1/type/constraint.py:538: DeprecationWarning: invalid escape sequence \*
    """
  /home/psycho/.local/share/virtualenvs/vf-CMjiR2h9/lib/python3.7/site-packages/pyasn1/type/namedval.py:54: DeprecationWarning: invalid escape sequence \*
    """
  /home/psycho/.local/share/virtualenvs/vf-CMjiR2h9/lib/python3.7/site-packages/zeep/xsd/visitor.py:405: DeprecationWarning: invalid escape sequence \[
    match = re.match('([^\[]+)', array_type)
  /home/psycho/.local/share/virtualenvs/vf-CMjiR2h9/lib/python3.7/site-packages/flask_ldap3_login/forms.py:26: DeprecationWarning: Required is going away in WTForms 3.0, use DataRequired
    username = wtforms.StringField('Username', validators=[validators.Required()])
  /home/psycho/.local/share/virtualenvs/vf-CMjiR2h9/lib/python3.7/site-packages/flask_ldap3_login/forms.py:27: DeprecationWarning: Required is going away in WTForms 3.0, use DataRequired
    password = wtforms.PasswordField('Password', validators=[validators.Required()])
  /home/psycho/.local/share/virtualenvs/vf-CMjiR2h9/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
    'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '

-- Docs: https://docs.pytest.org/en/latest/warnings.html


```

**Comment by nickw444** [comment] 2018-12-02 07:54
Hi @psychomantys would you be able to give me a code sample of how you are creating your application and how you are instantiating it when testing it? This will help me understand how to reproduce the issue and subsequently fix this issue. 

Thanks

**Comment by psychomantys** [comment] 2018-12-02 20:52
Yes, yes, great idea, and you can see if I'm doing something wrong too!

I started doing it using **pytest-flask**, but as I did not know exactly what was giving error, I did manually with **pytest**.

The code to create the app on **vf/__init__.py**:

```python
def create_app(config=None, https_reverse_proxy=None, extra_config_file=None, show_debug_log=None):
	if show_debug_log:
		import logging
		logging.basicConfig(level=logging.DEBUG)

	# create and configure the app
	app=Flask(__name__)

	root_dir=os.path.abspath(os.getcwd())

	if config is None:
		# load the instance config, if it exists, when not testing
		app.config.from_pyfile('config.cfg', silent=True)
	else:
		# load the test config if passed in
		app.config.from_mapping(config)

	if extra_config_file:
		with open(extra_config_file) as f:
			local_config=json.load(f)
			app.config.update(local_config)

	with app.app_context():
		# Load url handlers
		import vf.urlhandler1.ws_api

		# LDAP auth
		from vf.auth.ldap_login import login_manager
		login_manager.init_app(app)

		from vf.auth.ldap_login import ldap_manager
		ldap_manager.init_app(app)

		from vf.auth.flask_principal import permission_manager
		permission_manager.init_app(app)

		from vf.db import db
		db.init_app(app)

	# ensure the instance folder exists
	try:
		os.makedirs(app.instance_path)
	except OSError:
		pass

	if https_reverse_proxy:
		app.wsgi_app=Reverse_proxy(
			app.wsgi_app,
			script_name=https_reverse_proxy,
			scheme='https',
			override_path_info=False
		)

	return app
```

And the tests on **tests/test_login.py**:

```python
import pytest
import flask
from flask import url_for

from vf import create_app

@pytest.mark.usefixtures("client")
def test_login_logout(client):
	"""Make sure login and logout works."""
	rv=login(client, 'psycho', 'rigthpassword')
	assert(b'Invalid Username/Password' not in rv.data)
	assert(b'Por favor, se identifique' not in rv.data)

	rv=logout(client)
	assert(b'Por favor, se identifique' in rv.data)

	rv=login(client, 'psychox', 'rigthpassword')
	assert(b'Invalid Username/Password' in rv.data)

	rv=login(client, 'psycho', 'wrongpassword')
	assert(b'Invalid Username/Password' in rv.data)

@pytest.mark.usefixtures("client")
def test_login_logout_2(client):
	"""Make sure login and logout works."""

	rv=login(client, 'psycho', 'rigthpassword')
	assert(b'Invalid Username/Password' not in rv.data)
	assert(b'Por favor, se identifique' not in rv.data)

	rv=logout(client)
	assert(b'Por favor, se identifique' in rv.data)

	rv=login(client, 'psychox', 'rigthpassword')
	assert(b'Invalid Username/Password' in rv.data)

	rv=login(client, 'psycho', 'wrongpassword')
	assert(b'Invalid Username/Password' in rv.data)
```

And the code for the fixtures:

```python
#!/usr/bin/env python

import pytest
import flask
from flask import url_for

from vf import create_app

@pytest.fixture
def client():
	app=create_app(
		extra_config_file="utils/config_test.cfg",
		config={
			"WTF_CSRF_ENABLED": False,
			"SERVER_NAME": "dummy.org"
		})
	client=app.test_client()

	ctx=app.app_context()
	ctx.push()

	yield client, app

	ctx.pop()

	del client
	del app

def login(client, username, password):
	return client[0].post(url_for('login'), data=dict(
		username=username,
		password=password
	), follow_redirects=True)

def logout(client):
	return client[0].get(url_for('logout'), follow_redirects=True)
```

If there is anything else I can do, please let me know.

**Comment by nickw444** [comment] 2019-01-01 20:46
Hi @psychomantys thanks for the code, I will try to work on a solution to the issue this week 👍

**Comment by nickw444** [comment] 2019-08-06 23:07
I began working on a v2 of this library in January to set out to solve this issue and cleanup the general code architecture, however after a long internal debate, I have made the difficult decision that I will no longer be actively maintaining this repo. 

I am now in the process of finding a new maintainer - if this is something that may interest you, you can find more details in the [README](https://github.com/nickw444/flask-ldap3-login#maintainer-wanted)

**Comment by gmacon** [comment] 2019-08-24 20:35
I plan to attack this in two PRs:

1. A backwards-breaking PR removing `init_config` and providing documentation for suggested migration paths.
2. A PR that moves the state on `LDAP3LoginManager` to the Flask application context, which should fix this issue.

**Comment by nickw444** [comment] 2019-08-24 21:36
Sounds like a good plan to me @gmaconc, let me know if there’s anything info/context I can provide to help with the refactor.

**Closed** 2020-03-02 23:43 UTC
Labels: bug

**Comment by Mindslave** [comment] 2020-12-30 11:44
Hey,
I came across the issue described here just now, essentially I have same problem that @psychomantys had. I'm using a `create_app` function to create multiple instances of the application during testing with pytest.

```
@pytest.fixture
def client():
    app = create_app()
    app.config['TESTING'] = True
    app.config['CSRF_ENABLED'] = False
    app.config['WTF_CSRF_ENABLED'] = False
    app.config['PRESERVE_CONTEXT_ON_EXCEPTION'] = False
    with app.test_client() as client:
        with app.app_context():
            yield client


@pytest.fixture
def no_auth_client():
    app = create_app()
    app.config['TESTING'] = True
    app.config['CSRF_ENABLED'] = False
    app.config['WTF_CSRF_ENABLED'] = False
    app.config['PRESERVE_CONTEXT_ON_EXCEPTION'] = False
    app.config['LOGIN_DISABLED'] = True
    with app.test_client() as client:
        with app.app_context():
            yield client
```

And I get the error:

```
    @pytest.fixture
    def client():
>       app = create_app()

tests/conftest.py:10: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
qxfc/__init__.py:22: in create_app
    ldap_manager.init_app(app)
../../../.local/share/virtualenvs/FileUpload-6Ch_x6zF/lib/python3.7/site-packages/flask_ldap3_login/__init__.py:77: in init_app
    self._server_pool.remove(s)
../../../.local/share/virtualenvs/FileUpload-6Ch_x6zF/lib/python3.7/site-packages/ldap3/core/pooling.py:300: in remove
    self._pool_state.refresh()
../../../.local/share/virtualenvs/FileUpload-6Ch_x6zF/lib/python3.7/site-packages/ldap3/core/pooling.py:74: in refresh
    self.last_used_server = randint(0, len(self.server_states) - 1)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/random.py:222: in randint
    return self.randrange(a, b+1)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <random.Random object at 0x7fa18a83c018>, start = 0, stop = 0, step = 1, _int = <class 'int'>

    def randrange(self, start, stop=None, step=1, _int=int):
        """Choose a random item from range(start, stop[, step]).
    
        This fixes the problem with randint() which includes the
        endpoint; in Python this is usually not what you want.
    
        """
    
        # This code is a bit messy to make it fast for the
        # common case while still doing adequate error checking.
        istart = _int(start)
        if istart != start:
            raise ValueError("non-integer arg 1 for randrange()")
        if stop is None:
            if istart > 0:
                return self._randbelow(istart)
            raise ValueError("empty range for randrange()")
    
        # stop argument supplied.
        istop = _int(stop)
        if istop != stop:
            raise ValueError("non-integer stop for randrange()")
        width = istop - istart
        if step == 1 and width > 0:
            return istart + self._randbelow(width)
        if step == 1:
>           raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
E           ValueError: empty range for randrange() (0,0, 0)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/random.py:200: ValueError
======================================================================================================= short test summary info ========================================================================================================
ERROR tests/test_auth.py::test_redirects - ValueError: empty range for randrange() (0,0, 0)
```

which seems to come from 
```
qxfc/__init__.py:22: in create_app
    ldap_manager.init_app(app)
```

Is there anything that I am just doing wrong? Or is this bug just still around?

**Comment by gmacon** [comment] 2021-01-06 02:21
This fix hasn't been included in a release yet. I haven't had a ton of time to look at this code recently, and the codebase is currently in a sort of halfway state where we've made breaking changes from the previous release, but there are still things we want to get done before the 1.0 release. Feel free to work on the issues in the 1.0 milestone if you have time. I'll try to review PRs within a couple days if anyone opens any.

**Comment by psychomantys** [comment] 2021-09-29 18:14
Ah, very good, thanks for sharing this!

**Comment by Nantero1** [comment] 2021-09-29 18:36
@gmacon why is this dirty workaround still necessary? I think you merged a fix a year ago, I just started using the package and I am a little bit confused why I am having this problem at all in 2021.
